"""
NSS X - Interactive Demo Dashboard
Streamlit dashboard for demonstrating NSS capabilities.
Run with: streamlit run scripts/dashboard_demo.py
"""

import sys
from pathlib import Path

# Add src to path
sys.path.insert(0, str(Path(__file__).parent.parent))

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

from src.data import get_data_provider, COUNTRY_PROFILES

# Page config
st.set_page_config(
    page_title="NSS X - National Spatial Strategy",
    page_icon="🗺️",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS
st.markdown("""
<style>
    .main-header {
        font-size: 2.5rem;
        font-weight: bold;
        color: #1E3A5F;
        margin-bottom: 0;
    }
    .sub-header {
        font-size: 1.2rem;
        color: #666;
        margin-top: 0;
    }
    .metric-card {
        background-color: #f0f2f6;
        border-radius: 10px;
        padding: 20px;
        margin: 10px 0;
    }
    .warning-banner {
        background-color: #fff3cd;
        border: 1px solid #ffc107;
        border-radius: 5px;
        padding: 10px;
        margin-bottom: 20px;
    }
</style>
""", unsafe_allow_html=True)


@st.cache_resource
def get_provider(profile: str, seed: int):
    """Get cached data provider."""
    return get_data_provider('simulation', profile=profile, seed=seed)


@st.cache_data
def load_all_data(_provider, year: int):
    """Load all data from provider (cached)."""
    return {
        'regions': _provider.get_spatial_units(level=2).data,
        'settlements': _provider.get_settlements().data,
        'population': _provider.get_population(spatial_level=2, year=year).data,
        'economic': _provider.get_economic_data('gdp', spatial_level=2, year=year).data,
        'roads': _provider.get_infrastructure('roads').data,
        'projects': _provider.get_projects().data
    }


def main():
    # Header
    st.markdown('<p class="main-header">🗺️ NSS X - National Spatial Strategy</p>', unsafe_allow_html=True)
    st.markdown('<p class="sub-header">Sistema Nacional de Decisão Espacial | Demo Dashboard</p>', unsafe_allow_html=True)
    
    # Simulation warning banner
    st.markdown("""
    <div class="warning-banner">
        ⚠️ <strong>SIMULATION MODE</strong> - This dashboard uses synthetic data generated by the Simulation Engine.
        In production, the same interface connects to real data sources.
    </div>
    """, unsafe_allow_html=True)
    
    # Sidebar
    st.sidebar.header("⚙️ Configuration")
    
    profile = st.sidebar.selectbox(
        "Country Profile",
        options=list(COUNTRY_PROFILES.keys()),
        format_func=lambda x: COUNTRY_PROFILES[x].name
    )
    
    seed = st.sidebar.number_input("Random Seed", value=42, min_value=1, max_value=9999)
    year = st.sidebar.slider("Reference Year", 2020, 2050, 2025)
    
    st.sidebar.markdown("---")
    st.sidebar.markdown("### Profile Info")
    p = COUNTRY_PROFILES[profile]
    st.sidebar.write(f"**Population:** {p.total_population:,}")
    st.sidebar.write(f"**Area:** {p.total_area_sqkm:,.0f} km²")
    st.sidebar.write(f"**Regions:** {p.num_regions}")
    st.sidebar.write(f"**GDP:** ${p.gdp_billion_usd:.0f}B")
    
    # Load data
    provider = get_provider(profile, seed)
    data = load_all_data(provider, year)
    
    # Key metrics
    st.header("📊 Key Indicators")
    
    col1, col2, col3, col4, col5 = st.columns(5)
    
    total_pop = data['population']['population'].sum()
    total_gdp = data['economic']['gdp_billion_usd'].sum()
    n_settlements = len(data['settlements'])
    n_projects = len(data['projects'])
    road_km = data['roads']['length_km'].sum()
    
    col1.metric("Population", f"{total_pop/1e6:.1f}M")
    col2.metric("GDP", f"${total_gdp:.0f}B")
    col3.metric("Settlements", f"{n_settlements}")
    col4.metric("Major Projects", f"{n_projects}")
    col5.metric("Road Network", f"{road_km:,.0f} km")
    
    # Tabs
    tab1, tab2, tab3, tab4, tab5 = st.tabs([
        "🗺️ Spatial Overview",
        "👥 Demographics",
        "💰 Economy",
        "🏗️ Infrastructure",
        "📈 Analytics"
    ])
    
    with tab1:
        st.subheader("Spatial Overview")
        
        col1, col2 = st.columns(2)
        
        with col1:
            # Regions map
            fig = px.choropleth_mapbox(
                data['regions'],
                geojson=data['regions'].geometry.__geo_interface__,
                locations=data['regions'].index,
                color='area_sqkm',
                hover_name='name_en',
                hover_data=['area_sqkm'],
                mapbox_style="carto-positron",
                center={"lat": p.center_lat, "lon": p.center_lon},
                zoom=4,
                opacity=0.7,
                title="Regions by Area"
            )
            fig.update_layout(margin={"r":0,"t":30,"l":0,"b":0}, height=400)
            st.plotly_chart(fig, use_container_width=True)
        
        with col2:
            # Settlements scatter
            fig = px.scatter_mapbox(
                data['settlements'],
                lat=data['settlements'].geometry.y,
                lon=data['settlements'].geometry.x,
                size='population',
                color='hierarchy_class',
                hover_name='name_en',
                hover_data=['population', 'hierarchy_class'],
                mapbox_style="carto-positron",
                center={"lat": p.center_lat, "lon": p.center_lon},
                zoom=4,
                size_max=30,
                title="Settlements by Population"
            )
            fig.update_layout(margin={"r":0,"t":30,"l":0,"b":0}, height=400)
            st.plotly_chart(fig, use_container_width=True)
    
    with tab2:
        st.subheader("Demographics")
        
        col1, col2 = st.columns(2)
        
        with col1:
            # Population by region
            fig = px.bar(
                data['population'].sort_values('population', ascending=True),
                x='population',
                y='name_en',
                orientation='h',
                title="Population by Region",
                labels={'population': 'Population', 'name_en': 'Region'}
            )
            fig.update_layout(height=400)
            st.plotly_chart(fig, use_container_width=True)
        
        with col2:
            # Settlement hierarchy
            hierarchy_counts = data['settlements']['hierarchy_class'].value_counts()
            fig = px.pie(
                values=hierarchy_counts.values,
                names=hierarchy_counts.index,
                title="Settlement Hierarchy Distribution"
            )
            fig.update_layout(height=400)
            st.plotly_chart(fig, use_container_width=True)
        
        # Top settlements table
        st.subheader("Top 10 Settlements")
        top_settlements = data['settlements'].nlargest(10, 'population')[
            ['name_en', 'population', 'hierarchy_class', 'region_id']
        ].reset_index(drop=True)
        top_settlements.index += 1
        st.dataframe(top_settlements, use_container_width=True)
    
    with tab3:
        st.subheader("Economic Indicators")
        
        col1, col2 = st.columns(2)
        
        with col1:
            # GDP by region
            fig = px.bar(
                data['economic'].sort_values('gdp_billion_usd', ascending=True),
                x='gdp_billion_usd',
                y='name_en',
                orientation='h',
                title="GDP by Region (Billion USD)",
                labels={'gdp_billion_usd': 'GDP (B USD)', 'name_en': 'Region'}
            )
            fig.update_layout(height=400)
            st.plotly_chart(fig, use_container_width=True)
        
        with col2:
            # GDP per capita
            fig = px.bar(
                data['economic'].sort_values('gdp_per_capita_usd', ascending=True),
                x='gdp_per_capita_usd',
                y='name_en',
                orientation='h',
                title="GDP per Capita (USD)",
                labels={'gdp_per_capita_usd': 'GDP/capita', 'name_en': 'Region'}
            )
            fig.update_layout(height=400)
            st.plotly_chart(fig, use_container_width=True)
        
        # Projects
        st.subheader("Major Projects")
        
        col1, col2 = st.columns(2)
        
        with col1:
            status_counts = data['projects']['status'].value_counts()
            fig = px.pie(
                values=status_counts.values,
                names=status_counts.index,
                title="Projects by Status"
            )
            st.plotly_chart(fig, use_container_width=True)
        
        with col2:
            sector_counts = data['projects']['sector'].value_counts()
            fig = px.bar(
                x=sector_counts.index,
                y=sector_counts.values,
                title="Projects by Sector",
                labels={'x': 'Sector', 'y': 'Count'}
            )
            st.plotly_chart(fig, use_container_width=True)
    
    with tab4:
        st.subheader("Infrastructure")
        
        col1, col2 = st.columns(2)
        
        with col1:
            # Road network by class
            road_stats = data['roads'].groupby('road_class')['length_km'].sum().reset_index()
            fig = px.bar(
                road_stats,
                x='road_class',
                y='length_km',
                title="Road Network by Class",
                labels={'road_class': 'Class', 'length_km': 'Length (km)'}
            )
            st.plotly_chart(fig, use_container_width=True)
        
        with col2:
            # Road metrics
            st.markdown("### Road Network Statistics")
            st.write(f"**Total Length:** {road_km:,.0f} km")
            st.write(f"**Highway Length:** {data['roads'][data['roads']['road_class']=='highway']['length_km'].sum():,.0f} km")
            st.write(f"**Primary Roads:** {data['roads'][data['roads']['road_class']=='primary']['length_km'].sum():,.0f} km")
            st.write(f"**Network Density:** {road_km/p.total_area_sqkm*1000:.2f} km/1000km²")
    
    with tab5:
        st.subheader("Spatial Analytics")
        
        col1, col2, col3 = st.columns(3)
        
        # Calculate metrics
        top_cities = data['settlements'].nlargest(4, 'population')
        primacy = top_cities['population'].iloc[0] / top_cities['population'].iloc[1:4].sum()
        
        pop_values = data['population']['population'].sort_values().values
        n = len(pop_values)
        gini = (2 * sum((i + 1) * v for i, v in enumerate(pop_values))) / (n * pop_values.sum()) - (n + 1) / n
        
        gdp_shares = data['economic']['gdp_billion_usd'] / data['economic']['gdp_billion_usd'].sum()
        hhi = (gdp_shares ** 2).sum()
        
        with col1:
            st.metric("Urban Primacy Index", f"{primacy:.2f}")
            st.caption("Ratio of largest city to next 3 cities")
        
        with col2:
            st.metric("Population Gini", f"{gini:.3f}")
            st.caption("Spatial inequality (0=equal, 1=concentrated)")
        
        with col3:
            st.metric("Economic HHI", f"{hhi:.3f}")
            st.caption("Economic concentration (0=dispersed, 1=concentrated)")
        
        # Lorenz curve
        st.subheader("Population Distribution (Lorenz Curve)")
        
        cum_pop = data['population']['population'].sort_values().cumsum()
        cum_pop_pct = cum_pop / cum_pop.max() * 100
        x_axis = list(range(1, len(cum_pop_pct) + 1))
        x_pct = [x / len(x_axis) * 100 for x in x_axis]
        
        fig = go.Figure()
        fig.add_trace(go.Scatter(x=x_pct, y=cum_pop_pct.values, name="Actual", line=dict(color='blue')))
        fig.add_trace(go.Scatter(x=[0, 100], y=[0, 100], name="Perfect Equality", line=dict(dash='dash', color='gray')))
        fig.update_layout(
            title="Population Lorenz Curve",
            xaxis_title="Cumulative % of Regions",
            yaxis_title="Cumulative % of Population",
            height=400
        )
        st.plotly_chart(fig, use_container_width=True)
    
    # Footer
    st.markdown("---")
    st.markdown("""
    <div style='text-align: center; color: #666;'>
        <p>NSS X - National Spatial Strategy System | Technology & Integration Lead: Global6 Advisors</p>
        <p>🔵 Simulation Mode - Data generated by Simulation Engine</p>
    </div>
    """, unsafe_allow_html=True)


if __name__ == "__main__":
    main()
